# Generated by Django 4.0 on 2024-03-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contacttable_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttable',
            name='membership',
            field=models.CharField(choices=[('S', 'SILVER'), ('G', 'GOLD'), ('D', 'DIAMOND')], default='S', max_length=1),
        ),
    ]
